//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Pedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante
    {
        public int ID_Comprobante { get; set; }
        public Nullable<int> ID_Pedido { get; set; }
        public string Tipo_Comprobante { get; set; }
        public Nullable<System.DateTime> Fecha_Emision { get; set; }
        public Nullable<decimal> Subtotal_Comp { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Igv { get; set; }
        public Nullable<decimal> Valor_Total { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
