//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Pedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Pedido
    {
        public int ID_Detalle { get; set; }
        public Nullable<int> ID_Pedido { get; set; }
        public Nullable<int> ID_Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio_Venta { get; set; }
        public Nullable<decimal> Subtotal_Prod { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
